# Generated by Django 3.0.5 on 2020-04-06 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='referer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='url_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_shortener.URL_Code'),
        ),
    ]
