# Generated by Django 3.0.5 on 2020-04-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField(verbose_name='date created')),
                ('com_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
