# Generated by Django 3.0.4 on 2020-04-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grocery_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_item', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='date completed')),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
