# Generated by Django 3.0.5 on 2020-04-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_remove_groceryitem_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
