# Generated by Django 3.0.5 on 2020-04-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_text', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(verbose_name=' date created')),
                ('completed_date', models.DateField(verbose_name='Date completed')),
            ],
        ),
        migrations.CreateModel(
            name='AddedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_item_text', models.CharField(max_length=20)),
                ('groceryItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_list.GroceryItem')),
            ],
        ),
    ]
