# Generated by Django 3.0.5 on 2020-04-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_click'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='url',
            new_name='click_url',
        ),
    ]
