# Generated by Django 3.0.5 on 2020-04-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0003_auto_20200406_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='referral',
            field=models.TextField(null=True),
        ),
    ]
