# Generated by Django 3.0.5 on 2020-04-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0004_click_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='referral',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
