# Generated by Django 3.0.5 on 2020-04-06 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLinkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=16)),
                ('user_agent', models.CharField(max_length=255)),
                ('times_clicked', models.IntegerField(default=1)),
                ('link_clicked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_shortener.UrlShortener')),
            ],
        ),
    ]
